ANDROID: f2fs: fix build error on PAGE_KERNEL_RO
This fixes build error reported by kbuild test robot.

tree:   https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-stable.git linux-4.14.y
head:   2945d197414d9732c680ea0b709735d3b0d8ea57
commit: f6574fbf6578e47cfa3cace486ca852979a1e433 [868/885] f2fs: support data compression
config: mips-allyesconfig (attached as .config)
compiler: mips-linux-gcc (GCC) 7.5.0
reproduce:
        wget https://raw.githubusercontent.com/intel/lkp-tests/master/sbin/make.cross -O ~/bin/make.cross
        chmod +x ~/bin/make.cross
        git checkout f6574fbf6578e47cfa3cace486ca852979a1e433
        # save the attached .config to linux build tree
        GCC_VERSION=7.5.0 make.cross ARCH=mips

If you fix the issue, kindly add following tag
Reported-by: kbuild test robot <lkp@intel.com>

All errors (new ones prefixed by >>):

   fs/f2fs/compress.c: In function 'f2fs_compress_pages':
>> fs/f2fs/compress.c:359:56: error: 'PAGE_KERNEL_RO' undeclared (first use in this function); did you mean
+'PAGE_KERNEL_NC'?
     cc->rbuf = vmap(cc->rpages, cc->cluster_size, VM_MAP, PAGE_KERNEL_RO);
                                                           ^~~~~~~~~~~~~~
                                                           PAGE_KERNEL_NC
   fs/f2fs/compress.c:359:56: note: each undeclared identifier is reported only once for each function it appears
+in
   fs/f2fs/compress.c: In function 'f2fs_decompress_pages':
   fs/f2fs/compress.c:456:56: error: 'PAGE_KERNEL_RO' undeclared (first use in this function); did you mean
+'PAGE_KERNEL_NC'?
     dic->cbuf = vmap(dic->cpages, dic->nr_cpages, VM_MAP, PAGE_KERNEL_RO);
                                                           ^~~~~~~~~~~~~~
                                                           PAGE_KERNEL_NC

vim +359 fs/f2fs/compress.c
Change-Id: If921073482232ddddef2e65cc7a7c3e9ae6af008
Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
(cherry picked from commit 2abecdfec86d95eacd8b10c72f0c7b17fba5ab0f)